name: Norfair00 Profile metrics
on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  norfair00-profile:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Norfair00 Profile
        uses: lowlighter/metrics@latest
        with:
          config_timezone: Europe/Paris
          filename: metrics/profile.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, repositories, metadata
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: 76561198082577090
          plugin_steam_sections: recently-played
          plugin_steam_achievements_limit: 10
          plugin_steam_games_ignored: 629520,400040,388080