name: Waka

on:
  schedule:
    - cron: '3 */12 * * *' # every 12 hours
  push:
    branches:
      - master

jobs:
  update-waka:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_SHORT_INFO: "False" 
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_PROFILE_VIEWS:  "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_LOC_CHART: "False" 
          SHOW_TIMEZONE:  "True"
          SHOW_EDITORS:  "True"
